### ISSUE TITLE
Claridad de lectura en instrucciones

### ISSUE THREAD

**Issue by KryEdge** [frankvega2010/Fee#1]
En la pagina de instrucciones, el indicador del click izquierdo puede ser poco claro. Como recomendacion diria pintar el boton del mouse de un color (talvez del mismo tono de amarillo que el highlight) para mas claridad.

**Comment by frankvega2010** [comment]
FIXED. Mejoramos el tutorial, y agregamos tutoriales para las ugprades y el gameplay.
PD: Recomiendo reiniciar todos los datos al probar la nueva version, para hacer esto tienen que tocar la tecla "P" 3 veces en EL MENU PRINCIPAL. Si lo hicieron bien va a aparecer un boton a la esquina, lo apretan y se recarga el menu con los datos borrados. Digo esto porque el tutorial se abre solo la primera vez que lo juegan, y necesito verificar que funcionen bien esos eventos!
