### ISSUE TITLE
Sugerencia legibilidad Upgrades

### ISSUE THREAD

**Issue by KryEdge** [frankvega2010/Fee#10]
En la pantalla de upgrades, el "tower fire rate" y el "meteor cooldown" tienen su valor current que se modifica con el nivel. Es obvio que son segundos, pero por si acaso añadiría una unidad después del numero para que no haya posibles confusiones del usuario.

https://drive.google.com/open?id=1SVaWj6GRbmmn5ZcNJYV81qq0J6V2B_JC

**Comment by ferpg** [comment]
@frankvega2010 Disculpá que te moleste (soy el profe del trayecto de testing) ¿Podríamos comentarnos el motivo del cierre? Es más que nada para que sepamos qué no tenemos que subir en el futuro o para verificar si quisiste marcarlo como "FIXED". En caso de que la respuesta sea la segunda opción, todavía tendríamos que verificarlo. Cualquier cosa mandamos un mail ¡Saludos!

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
@KryEdge Marcar como closed. Ya figuran segundos.
