### ISSUE TITLE
Se puede posicionar torretas desde el menu de pausa

### ISSUE THREAD

**Issue by KryEdge** [frankvega2010/Fee#11]
Si pauso el juego mientras tengo la posibilidad de posicionar una torreta, y muevo el mouse, el juego me permite posicionar una torreta donde quiera sin restricciones.

Paso 1: Entrar una partida.
Paso 2: Pausar el juego mientras el indicador de posiciona torreta este en verde.
Paso 3: Posicionar torreta donde queramos en el mapa visible.

Esto se debe a que el chequeo de posicionamiento lo realiza mientras esta el juego en ejecucion, entonces una vez que pausamos el chequeo queda en "true", y nos permite posicionarla en cualquier lugar. 
Se debería cambiar o el chequeo, o mas apropiadamente, no debería dejar que el jugador mueva el indicador (osea el icono de la torreta, o el semicírculo del meteoro) mientras el juego este pausado.

https://drive.google.com/open?id=11x-Fc5XfMPXyXxP0NffLIuRD8SPW3hFG
https://drive.google.com/open?id=1bNKMe7RwLLm5IJ5kYiK1g9E5CxMB-996

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
Se corroboró que ya está fixed. @KryEdge @ferpg . Marcar como Closed
