### ISSUE TITLE
Bug Hadas Voladoras

### ISSUE THREAD

**Issue by KryEdge** [frankvega2010/Fee#12]
A causa del bug #11 las hadas se chocan contra las torretas y pueden salir volando, ademas de destruir su pathing, haciendo que caminen entre los arboles o en cualquier lado. Ademas se observa un comportamiento en el que las hadas van derecho hacia las torretas por alguna razon (probablemente por la logica del pathing asumo)

Paso 1: Replicar bug #11 
Paso 2: Esperar que las hadas se choquen con las torretas (no siempre ocurre, a veces solo se mueven un poco hacia atras)
Paso 3: Enjoy

Este bug debería ser solucionado en conjunto con el bug #11 

https://drive.google.com/open?id=1MmcI7oZm9JBJrKjejyPXRluoFsyH3uAU

**Comment by frankvega2010** [comment]
FIXED (Al arreglar el Issue #11)

**Comment by Leeoofeer** [comment]
@frankvega2010 Franco buenas, voy a estar re-chequeando los bugs, así que te quería pedir que subas la build del proyecto asi es mas facil al no tener que estar usando unity.

**Comment by frankvega2010** [comment]
> @frankvega2010 Franco buenas, voy a estar re-chequeando los bugs, así que te quería pedir que subas la build del proyecto asi es mas facil al no tener que estar usando unity.

Hola! Te aviso que el juego esta siempre actualizado en la pagina de itchio , te lo dejo aca https://beldam-games.itch.io/fee . Cualquier cosa manda mensaje aca o sino contactame por mail

**Comment by Leeoofeer** [comment]
@KryEdge  Parece estar fixed al arreglar el #11 . Marcar como closed
