### ISSUE TITLE
La camara se mueve en menu de pausa

### ISSUE THREAD

**Issue by Leeoofeer** [frankvega2010/Fee#13]
Descripción
--
La cámara puede seguir moviéndose mientra el juego esta en pausa.

Pasos para reproducir
--
1-In game, poner el juego en pausa
2-Apretar la tecla space

Resultado:
La cámara va hacia las hadas. En algunos casos la cámara se queda girando al rededor del mundo y no se puede parar (difícil de reproducir esto con exactitud)

Resolución
--
Solo permitir la navegación en el menú mientras el juego está en pausa.

Video
--
https://drive.google.com/open?id=1N0IhrmFj5gx0nlRc7ejZWYcGMLJiOvb4

**Comment by frankvega2010** [comment]
FIXED. Arreglado junto al Issue #3
