### ISSUE TITLE
Las barras de sonidos se les estira el sprite

### ISSUE THREAD

**Issue by Leeoofeer** [frankvega2010/Fee#14]
Descripción
--
Las barras de sonido sin completar están bien seteadas, lo que sucede es que cuando deslizamos el punto para incrementar el sonido, la barra completa parece que está estirando un sprite lo cual se nota visiblemente y también queda la barra vacía por fuera de la completa

Pasos para reproducir
--
1-Abrir menú de opciones
2-Deslizar lentamente la barra de "Music" / "Sound effects" hacia la derecha (incrementando el sonido)

Resultado:
Se deforma el sprite de la barra incremental de música/sonido.

Resolución
--
Cambiar el sprite de la barra de sonido, que no sea cuadrado y luego al estirarse ovalado/cilindrico.

Vídeo
--
https://drive.google.com/open?id=1e1NPIDwzZ4IlJGbEbhc2wkuT1HLF7C0j

labels: trivial, open

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
Fixed verified
