### ISSUE TITLE
El sonido se resetea a cero

### ISSUE THREAD

**Issue by Leeoofeer** [frankvega2010/Fee#15]
Descripción
--
Al incrementar el sonido en el menú de opciones al jugar no hay sonido, esto se debe a que al salir del menú de opciones el sonido se resetea a "mute"

Pasos para reproducir
--
1-Ir al menú de opciones
2-Incrementar la barra de Music y Effects
3-Volver al Main screen
4-Volver a entrar al menú de opciones

Resultado:
Las barras de sonido se van a resetear, dejando el juego sin sonido alguno.

Resolución
--
Guardar los valores del los volúmenes para que no se resetee al salir.

Vídeo
--
https://drive.google.com/open?id=1vdqSeu6fTSUJ54Bo6p8EgDMsdtUX5p0T

**Comment by frankvega2010** [comment]
FIXED
