### ISSUE TITLE
Boton "Home" del lore sin sonido

### ISSUE THREAD

**Issue by Leeoofeer** [frankvega2010/Fee#16]
Descripción
--
Al entrar al Lore y presionar el botón "Home" o "Back" no emite ningun sonido, y todos los otros botones de los menues si

Pasos para reproducir
--
1-Ir al Lore
2-Apretar el botón "Back" o "Home"

Resultado:
El botón es presionado y ningún sonido es emitido

Resolución
--
Agregar sonido al botón.

Vídeo
--
https://drive.google.com/open?id=1RXk3Fi-pkyPn34SDNCnqh2DDqclRLRL0

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
Fixed verified
