### ISSUE TITLE
Dialogo de ayuda de los objetivos no se cierra

### ISSUE THREAD

**Issue by Leeoofeer** [frankvega2010/Fee#17]
Descripción
--
Al presionar la tecla "Tab" tal y como dice el cartel de ayuda para abrir/cerrar el cuadro de los objetivos, este no desaparece. 
Este desaparece cuando se lanza un meteorito.

Pasos para reproducir
--
1-Iniciar una partida
2-Apretar la tecla "Tab" repetidas veces

Resultado:
El dialogo de ayuda no se cierra/desaparece.

Resolución
--
Agregar sonido al botón.

Vídeo
--
https://drive.google.com/open?id=14BzLW8KSAcadHShASgnYdmDhsl4hDhSu

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
Si aprieto TAB el cuadro se cierra y no pasa al siguiente cuadro de dialogo.
Cuando tiro meteoros el cuadro de meteoros no se cierra y pasa al siguiente.
Cuando aprieto E el cuadro no se cierra y pasa al siguiente.

Debería funcionar de la siguiente manera:
https://drive.google.com/open?id=1o3db4rVqu5lptkzwnlFXrgPjZJQ0h2fu

Luego, si no termino los tutoriales y aprieto para que me los muestre y cierro las ventanas, al generar una acción que genere algún tutorial el cuadro de dialogo aparece solo. Ver el siguiente video:
https://drive.google.com/open?id=1xbfo6qqIdf-TSUXwXkLc_IwrC20E-2w7

**Comment by frankvega2010** [comment]
FIXED. Los tutoriales empiezan a salir a medida que haces determinadas acciones y al cerrarse no pasan al siguiente tutorial, pasa lo mismo si tocas el boton del tutorial : no se va a pasar al siguiente tutorial hasta que aprietes el boton o hagas otra accion.

**Comment by Leeoofeer** [comment]
Okay, fix verified, lo cierro.
