### ISSUE TITLE
Comportamiento random de la cámara

### ISSUE THREAD

**Issue by Leeoofeer** [frankvega2010/Fee#18]
Descripción
--
Al querer centrar la cámara en modo pausa no sucede nada, pero cuando se quita la pausa esta acción sucede y provocando, a veces que la cámara se mueva sola.

Pasos para reproducir
--
1-Iniciar una partida
2-Poner pausa
3-Apretar "Space"
4-Sacar la pausa

Resultado:
La cámara empieza atener un comportamiento extraño

Resolución
--
Al estar en modo pausa el juego no debe tomar ningún input ya que este queda "holdeado" hasta que se resume la partida.

Vídeo
--
https://drive.google.com/open?id=1T92uNMVn9KpUt1iOp2w9ZdeW1GX0FpgH

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
Fixed verified
