### ISSUE TITLE
Botón "Back" en el tuto de como subir de lvl no va

### ISSUE THREAD

**Issue by Leeoofeer** [frankvega2010/Fee#19]
Descripción
--
Al terminar la primera partida y encontrarse con el tutorial de como lvlear las cosas, aparece un botón "Back" en la primera screen y este no se debería encontrar ahí.

Pasos para reproducir
--
1-Iniciar una partida
2-Perder la partida
3-Apretar el botón back

Resultado:
El botón es presionado y ninguna acción es realizada.

Resolución
--
Eliminar el botón en dicha escena.

Vídeo
--
https://drive.google.com/open?id=1qPzi3_F_cvqPHc-z73xOeMySZV7KoQkS

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
Le agregaría sonido a las flechas, así como todos los botones lo poseen.
https://drive.google.com/open?id=1SrW17b970O1JENSmE3MucKZILeSrZ_T1

**Comment by Leeoofeer** [comment]
Fixed verified
