### ISSUE TITLE
El boton de Fullscreen no funciona

### ISSUE THREAD

**Issue by KryEdge** [frankvega2010/Fee#2]
Desde el menu de configuracion in-game. Si cambio la resolucion e intento agrandar la pantalla, el boton no responde.

Paso 1: Acceder a configuracion (una vez dentro del juego)
Paso 2: Cambiar la resolucion por una menor
Paso 3: Cambiar nuevamente a una resolucion mayor 
Paso 4: Clickear el boton fullscreen

Es posible que el bug se deba al menu de resoluciones, ya que puedo acceder a este haciendo click en el texto "fullscreen" a su derecha. Es posible que la hitbox este mal posicionada

**Comment by frankvega2010** [comment]
FIXED.

**Comment by frankvega2010** [comment]
Aparecio otro bug referido a esto, ya estoy al tanto pero va a estar arreglada para la proxima version. De todas formas revisarlo cuando suba la version nueva ahora

**Comment by Leeoofeer** [comment]
Lo que es cambio de resolución y fullscreen se siguen bugeando, adjunto video de demostracion.
Tiene un comportamiento raro pero en teoría unos pasos para reproducirlo es:
Pasos:
1-Abrir el juego en modo ventana.
2-Entrar a configuración.
Resultado:
El juego se pone en pantalla completa solo.

Luego de haber realizado los pasos anteriores realizar los siguientes:
Pasos:
1-Cambiar la resolución.

Resultado:
El juego se pone en modo ventana.
El botón de fullscreen aparece marcado.

Chequear en el vídeo como actúa el bug.
https://drive.google.com/open?id=1mt8KhScUhiDwwlnTo1C5GYG8lL7TKr6v
Espero nuevo FIX.

**Comment by frankvega2010** [comment]
FIXED
