### ISSUE TITLE
Diálogos de ayuda superpuestos

### ISSUE THREAD

**Issue by Leeoofeer** [frankvega2010/Fee#20]
Descripción
--
Al estar los diálogos de ayuda iniciales, si uno presiona el botón para que se vuelvan a mostrar, estos se llegan a superponer, inhabilitando la lectura de alguno de los dos.

Pasos para reproducir
--
1-Iniciar una partida con los datos de juegos en cero
2-Lanzar un meteorito
3-Poner una torreta/árbol
4-Apretar 2 veces el boton de dialogos (con forma de papiro)

Resultado:
Los cuadros de dialogo que están en la pantalla aparecen superpuestos.

Resolución
--
Permitir solo 1 cuadro de dialogo a la vez en la pantalla.

Vídeo
--
https://drive.google.com/open?id=16WWWCRS3EWco0EdzjIYAxpoiZsJcswuL

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
Fixed verified
