### ISSUE TITLE
Flechas del tuto de lvlup no poseen sonido

### ISSUE THREAD

**Issue by Leeoofeer** [frankvega2010/Fee#21]
Descripción
--
Al terminar la primera partida y encontrarse con el tutorial de como lvlear las cosas o si bien con un save file que haya terminado al menos una partida, al estar en la pantalla de como lvlear las habilidades, las felchas son los unicos botones del juego que no poseen sonido y resulta raro.

Pasos para reproducir
--
1-Iniciar una partida
2-Perder la partida
3-Apretar el boton de lvlear habilidades
4-Apretar las flechas de avance/retroceso

Resultado:
Los botones no emiten sonido

Resolución
--
Agregar sonidos a los botones de flechas

Vídeo
--
https://drive.google.com/open?id=1SrW17b970O1JENSmE3MucKZILeSrZ_T1

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
Fixed verified
