### ISSUE TITLE
Slidebar upgrades con sprite superpuesto

### ISSUE THREAD

**Issue by Leeoofeer** [frankvega2010/Fee#22]
Descripción
--
Al estar en la ventana de upgrades, se siente raro que la barra dentro del slide bar se superponga con las flechas del limite de la misma, agregando que en la parte de arriba se puede ver una puntita de la flecha y en la parte de abajo no (cuando esta al limite de arriba/cuando esta al limite de abajo)

También sucede lo mismo con la barra de resoluciones en el menu de opciones, tanto en el in game, como el del main menu, salvo que en este termina de superponer a las flechas.

Pasos para reproducir
--
1-Ir a la pantalla de upgrades
2-Mover de arriba hacia abajo chocando con los limites la slidebar

1-Ir al menu de opciones
2-Abrir el slide de resoluciones
3-Mover de arriba hacia abajo chocando con los limites la slidebar

1-Iniciar una partida
2-Ir a configuraciones
2-Abrir el slide de resoluciones
3-Mover de arriba hacia abajo chocando con los limites la slidebar

Resultado:
Se superpone el ovalo(boton) del slidebar con los limites de la misma

Resolución
--
No permitir que la barra llegue a las flechas

Vídeo
--
https://drive.google.com/open?id=1ktZRLt1ksuxhEDIJlkO_QAXObYBi362k

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
Bueno, pasa otra cosa rara ahora, al hacer click en las flechas se ve chiquita la "pastilla" y vibra.
Video:
https://drive.google.com/open?id=10NW5e52eAwS_xzu12X0m3PTD_e26xHmS
Y con la ruedita:
https://drive.google.com/open?id=1TLWmKpsqkTeWx6rSb01oUPirr5QZesac

**Comment by Leeoofeer** [comment]
Agrego acá, que se puede hacer slide con el click fuera del recuadro de upgrades.
https://drive.google.com/open?id=1iDbcdL055fJiTXjeI6uHkXsBsnI77leM
Quedaría mejor si solo fuera dentro del recuadro.

**Comment by frankvega2010** [comment]
FIXED . No pude hacer que el handler deje de vibrar pero lo acomode para que no se achique cuando llegue a los bordes, tambien ajuste la posibilidad de solo hacer slide dentro del panel de upgrades.

**Comment by Leeoofeer** [comment]
Ahora se siente demasiado raro que no llegue a los bordes la "pastilla"
![image](https://user-images.githubusercontent.com/44010149/70911771-5b720580-1ff1-11ea-998d-b32db1a39161.png)
No hay otra forma de solucionar lo de que se achique la pastilla?

Falta corregir en el slide de resoluciones, que la pastilla no se ponga por encima de los limites
![image](https://user-images.githubusercontent.com/44010149/70912142-169a9e80-1ff2-11ea-8845-01e19b5f9293.png)

**Comment by frankvega2010** [comment]
FIXED. Pude arreglar los scrollbars de las resoluciones (En el menu de opciones y en la pausa), sin embargo el efecto de "rebote" en las esquinas no lo pude solucionar. Y a veces las pastillas de los scrollbars de las resoluciones se achican cuando vas a los bordes.

**Comment by Leeoofeer** [comment]
Se fixeo hasta donde se pudo, se cerrará
