### ISSUE TITLE
Error con "Stop Time" 

### ISSUE THREAD

**Issue by KryEdge** [frankvega2010/Fee#3]
Si presionamos escape mientras "Stop Time" esta activo y luego sacamos el escape o le damos al boton de resume. El tiempo se resume normalmente pero el boton de "Stop Time" queda encendido.

Paso 1: Abrir menu de Cheats
Paso 2: Clickear Stop Time
Paso 3: Apretar Escape
Paso 4: Apretar Escape otra vez o clickear el boton Resume

La posible soluciones es hacer que el tiempo siga pausado cuando vuelvo del menu de Escape. Posiblemente ambas lleven al mismo parametro "pause", se puede separar en dos parametros distintos, o bien realizar un chequeo de que no esta prendido el "Stop Time" antes de salir del menu de escape

PD: Si agregas un "ZA WARUDO" cuando prendo el cheat te doy puntos extra.

**Comment by frankvega2010** [comment]
FIXED. Les digo a los de audio que preparen los eventos para el Za warudo y Resume Time jajajajaj.

**Comment by frankvega2010** [comment]
me olvide de avisar, el stop time ahora se activa despues de un delay de unos 3 segundos (que es donde habria un audio).

**Comment by frankvega2010** [comment]
Update: Sonido integrado, va a estar disponible para la v0.11.

**Comment by Leeoofeer** [comment]
@frankvega2010 Cuando el stoptime está activo, no se puede mover nada, salva apretando "space" que mueve la camara y bugea los ejes de las torretas. Tambien, al sacar el stop time, la camara sale volando.

Dejo video de lo que pasa. 
https://drive.google.com/open?id=1R7wZcTXST_Oo_Boq1UvcxL6sJOFwsgxX

**Comment by frankvega2010** [comment]
FIXED. Realmente el stop time lo use para probar una cosa y quedo ahi, no sirve de mucho en sí. Pero arregle de que la camara no se pudiera mover mientras que el tiempo este parado o la partida este en pausa, para que no se rompa la camara.
