### ISSUE TITLE
Error posicionamiento de torretas

### ISSUE THREAD

**Issue by KryEdge** [frankvega2010/Fee#4]
Las torretas pueden ser posicionadas bastante lejos de los círculos de posicionamiento, como se observa en la foto.

Paso 1; Elegir Torretas
Paso 2: Posicionar el mouse sobre el área de posicionamiento
Paso 3: Alejar el mouse del área de posicionamiento
Paso 4: Click Izquierdo

Esto se puede deber a que lo que se chequea es que la hitbox de la torreta este cerca del área de posicionamiento. Una posible solución es que lo que se chequee sea la posición del mouse para ver si esta sobre el área indicada.

https://drive.google.com/open?id=1K2BwBJrf3u1c1qyvvTlo3ydMKT8oSuoN

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
@frankvega2010 Faltaría refinar un poco más el área donde se colocan las torretas. Dejo video de ejemplos.
https://drive.google.com/open?id=1HoTbfY0r3O6e9csHn0Zn9jMYMdSj3hxU

**Comment by frankvega2010** [comment]
FIXED. Por suerte es algo que note un tiempo antes de que me avisaras y lo arregle de antemano!
