### ISSUE TITLE
Error display Upgrades

### ISSUE THREAD

**Issue by KryEdge** [frankvega2010/Fee#5]
Una vez que hacemos click en jugar, en la pantalla de Upgrades, podemos clickear los iconos de las habilidades y, aunque no tengamos gemas, el icono cambiara para reflejar que se subió de nivel. Adjuntada foto del problema

Paso 1: Clickear en Play en el menú principal
Paso 2: Gastar todas las gemas 
Paso 3: Clickear en cualquier upgrade de nivel 1 o 2

Esto se solucionaría con el mismo chequeo que se hace para ver si el jugador puede o no comprar un determinado upgrade.

https://drive.google.com/open?id=1QSMrpgqCmuK2PyhfKEZBEuWIDHr9hGDf

**Comment by ferpg** [comment]
@frankvega2010 Disculpá que te moleste (soy el profe del trayecto de testing) ¿Podríamos comentarnos el motivo del cierre? Es más que nada para que sepamos qué no tenemos que subir en el futuro o para verificar si quisiste marcarlo como "FIXED". En caso de que la respuesta sea la segunda opción, todavía tendríamos que verificarlo. Cualquier cosa mandamos un mail ¡Saludos!

**Comment by frankvega2010** [comment]
Ah disculpa, me habia olvidado de ese paso jajajaaj. Ya arregle el bug, pero cuando subo los cambios en github automaticamente se cierra el Issue porque uso unas keywords especiales para no tener que cerrarlo a mano. El tema es que para que tengan que verificarlo tengo que subir la proxima version del juego, en tal caso voy poniendo FIXED en los comentarios y cualquier cosa podemos reabrir el issue.

**Comment by frankvega2010** [comment]
> Ah disculpa, me habia olvidado de ese paso jajajaaj. Ya arregle el bug, pero cuando subo los cambios en github automaticamente se cierra el Issue porque uso unas keywords especiales para no tener que cerrarlo a mano. El tema es que para que tengan que verificarlo tengo que subir la proxima version del juego, en tal caso voy poniendo FIXED en los comentarios y cualquier cosa podemos reabrir el issue.

No dije nada, ahi reabro el issue.

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
@KryEdge Ya hay sprites para cuando el lvl max se alcanzó y para cuando no se poseen las gemas suficientes. Marcar como closed.
