### ISSUE TITLE
Poca claridad en sprite del meteoro

### ISSUE THREAD

**Issue by KryEdge** [frankvega2010/Fee#6]
Cuando se lanza un meteoro, el semicírculo verde representa el área de impacto, pero el meteoro en cuestión es bastante mas pequeño, esto puede llevar a una mala lectura o a confusión por parte del usuario.

Paso 1: Entrar a una partida
Paso 2: Disparar un meteoro

Solución posible: Escalar el sprite del meteoro para que refleje mas fielmente el área de impacto

https://drive.google.com/open?id=19IjFmIHfWa9JLu2UP7RDeGFfOWOhYPdS

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
@KryEdge La explosión tiene mejor sprites. Marcar como closed.
