### ISSUE TITLE
Se muestra un grupo de numeros en el menu de pausa

### ISSUE THREAD

**Issue by KryEdge** [frankvega2010/Fee#8]
Cuando pausamos el juego, ya sea con P, Esc o el boton de pausa, se muestra en la parte superior de la pantalla "0000000000". No se si se debe a un asset faltante o alguna mala lectura de un codigo. O si puede estar relacionado al High Score (ya que aparecen casi a la misma altura). Foto adjuntada.

Paso 1: Entrar a una partida
Paso 2: Pausar el juego

https://drive.google.com/open?id=1XXZrbdu9ptuh03-_3Z0c9b4pcRuxzzGf

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
@KryEdge Ya no aparecen esos números. Marcar como closed.
