### ISSUE TITLE
El juego se resume si se minimiza

### ISSUE THREAD

**Issue by KryEdge** [frankvega2010/Fee#9]
Si el jugador pausa el juego y minimiza, al volver seguira viendo el menu de Pausa, pero el juego estare corriendo en el fondo. El juego resume una vez que se vuelve a maximizar la ventana (osea que mientras esta minimizado esta pausado, el problema es cuando se vuelve a maximizar la ventana).

Paso 1: Entrar a una partida
Paso 2: Pausar el juego
Paso 3: Minimizar ventana (con Alt + Tab) o con el boton de minimizar en modo ventana.
Paso 4: Abrir nuevamente la ventana del juego.

**Comment by frankvega2010** [comment]
FIXED

**Comment by Leeoofeer** [comment]
@KryEdge Marcar como closed. Minimizo estando en pausa, al+tab y todo y el juego no sigue corriendo.
